database:
  host: "localhost"
  port: "3307"
  name: "minecraft_crafting"
  user: "root"
  password: ""

# Enable debug mode (1 = enabled, 0 = disabled)
debug: 1

conjurer:
  mobs: |
    # obstinate_toltec_warrior
    # obstinate_toltec_hunter
    # obstinate_toltec_shaman
  recipe_drop_chance: 0.001
