name: MyCraftingPlugin2
version: '1.0-SNAPSHOT'
main: com.maks.mycraftingplugin2.Main
api-version: '1.20'
softdepend: [Vault, IngredientPouchPlugin, MythicMobs]
commands:
  crafting:
    description: Opens the crafting menu.
    usage: /crafting
    permission: mycraftingplugin.use
    permission-message: You don't have permission to use this command.
  editcrafting:
    description: Opens the crafting menu editor.
    usage: /editcrafting
    permission: mycraftingplugin.editlayout
    permission-message: You don't have permission to use this command.
  mine_shop:
    description: "Opens the mine shop crafting menu"
    usage: /mine_shop
    permission: mycraftingplugin.use
  edit_mine_shop:
    description: "Opens the mine shop crafting menu in edit mode"
    usage: /edit_mine_shop
    permission: mycraftingplugin.editlayout
  fisherman_shop:
    description: "Opens the fisherman shop crafting menu"
    usage: /fisherman_shop
    permission: mycraftingplugin.use
  edit_fisherman_shop:
    description: "Opens the fisherman shop crafting menu in edit mode"
    usage: /edit_fisherman_shop
    permission: mycraftingplugin.editlayout
  alchemy:
    description: "Open Alchemy menu"
    permission: mycraftingplugin.use
  edit_alchemy:
    description: "Open Alchemy menu in edit mode"
    permission: mycraftingplugin.editlayout
  jeweler:
    description: "Opens the jeweler menu"
    usage: /jeweler
    permission: mycraftingplugin.use
    aliases: [jew]
  edit_jeweler:
    description: "Opens the jeweler menu in edit mode"
    usage: /edit_jeweler
    permission: mycraftingplugin.editlayout
  jewels_crushing:
    description: "Opens the jewels crushing menu"
    usage: /jewels_crushing
    permission: mycraftingplugin.use
    aliases: [crushingj, jcrushing]
  gemologist:
    description: "Opens the gemologist menu"
    usage: /gemologist
    permission: mycraftingplugin.use
  edit_gemologist:
    description: "Opens the gemologist menu in edit mode"
    usage: /edit_gemologist
    permission: mycraftingplugin.editlayout
  gem_crushing:
    description: "Opens the gem crushing menu"
    usage: /gem_crushing
    permission: mycraftingplugin.use
  runemaster:
    description: "Opens the runemaster menu"
    usage: /runemaster
    permission: mycraftingplugin.use
  edit_runemaster:
    description: "Opens the runemaster menu in edit mode"
    usage: /edit_runemaster
    permission: mycraftingplugin.editlayout
  runes_crushing:
    description: "Opens the rune crushing menu"
    usage: /runes_crushing
    permission: mycraftingplugin.use
  emilia:
    description: "Opens Emilia's shop menu"
    usage: /emilia
    permission: mycraftingplugin.use
  edit_emilia:
    description: "Opens Emilia's shop menu in edit mode"
    usage: /edit_emilia
    permission: mycraftingplugin.editlayout
  zumpe:
    description: "Opens Zumpe shop menu"
    usage: /zumpe
    permission: mycraftingplugin.use
  edit_zumpe:
    description: "Opens Zumpe shop menu in edit mode"
    usage: /edit_zumpe
    permission: mycraftingplugin.editlayout
  conjurer_shop:
    description: "Opens the Conjurer menu"
    usage: /conjurer_shop
    permission: mycraftingplugin.use
  edit_conjurer_shop:
    description: "Opens the Conjurer menu in edit mode"
    usage: /edit_conjurer_shop
    permission: mycraftingplugin.editlayout
  scientist:
    description: "Opens the Scientist crafting category"
    usage: /scientist
    permission: mycraftingplugin.use
  edit_scientist:
    description: "Opens the Scientist category in edit mode"
    usage: /edit_scientist
    permission: mycraftingplugin.editlayout
  grave_shop:
    description: "Opens the grave shop crafting menu"
    usage: /grave_shop
    permission: mycraftingplugin.use
  edit_grave_shop:
    description: "Opens the grave shop crafting menu in edit mode"
    usage: /edit_grave_shop
    permission: mycraftingplugin.editlayout
  dungeon_shop:
    description: "Opens the dungeon shop crafting menu"
    usage: /dungeon_shop
    permission: mycraftingplugin.use
  edit_dungeon_shop:
    description: "Opens the dungeon shop crafting menu in edit mode"
    usage: /edit_dungeon_shop
    permission: mycraftingplugin.editlayout
  zoo_keeper:
    description: "Opens the zoo keeper crafting menu"
    usage: /zoo_keeper
    permission: mycraftingplugin.use
  edit_zoo_keeper:
    description: "Opens the zoo keeper crafting menu in edit mode"
    usage: /edit_zoo_keeper
    permission: mycraftingplugin.editlayout
  testjewels:
    description: Test jewel detection system
    usage: /<command> [help]
    permission: mycraftingplugin.testjewels
  testpouch:
    description: Test pouch integration
    usage: /<command> [check|inventory]
    permission: mycraftingplugin.testpouch
  imprinting:
    description: "Opens the set imprinting interface"
    usage: /imprinting
    permission: mycraftingplugin.use
    aliases: [imprint, setimprint]
  set_crushing:
    description: "Opens the set crushing interface"
    usage: /set_crushing
    permission: mycraftingplugin.use
    aliases: [setcrush, crushset]
  hefajsos:
    description: "Opens Hefajsos services menu"
    usage: /hefajsos
    permission: mycraftingplugin.use
    aliases: [hef, services]
permissions:
  mycraftingplugin.use:
    description: Allows the player to use the crafting menu.
    default: op
  mycraftingplugin.add:
    description: Allows the player to add new recipes.
    default: op
  mycraftingplugin.edit:
    description: Allows the player to edit recipes.
    default: op
  mycraftingplugin.editlayout:
    description: Allows the player to edit the crafting menu layout.
    default: op
  mycraftingplugin.premium:
    description: Allows the player to access premium tier items in Emilia shop.
    default: op
  mycraftingplugin.deluxe:
    description: Allows the player to access deluxe tier items in Emilia shop.
    default: op
  mycraftingplugin.testjewels:
    description: Allows testing of jewel detection system
    default: op
  mycraftingplugin.testpouch:
    description: Allows testing of pouch integration
    default: op
